// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mi_message.proto

#ifndef PROTOBUF_mi_5fmessage_2eproto__INCLUDED
#define PROTOBUF_mi_5fmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace medical_imaging {
class MsgPaging;
class MsgPagingDefaultTypeInternal;
extern MsgPagingDefaultTypeInternal _MsgPaging_default_instance_;
class MsgPoint2;
class MsgPoint2DefaultTypeInternal;
extern MsgPoint2DefaultTypeInternal _MsgPoint2_default_instance_;
class MsgRotate;
class MsgRotateDefaultTypeInternal;
extern MsgRotateDefaultTypeInternal _MsgRotate_default_instance_;
}  // namespace medical_imaging

namespace medical_imaging {

namespace protobuf_mi_5fmessage_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_mi_5fmessage_2eproto

// ===================================================================

class MsgPoint2 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:medical_imaging.MsgPoint2) */ {
 public:
  MsgPoint2();
  virtual ~MsgPoint2();

  MsgPoint2(const MsgPoint2& from);

  inline MsgPoint2& operator=(const MsgPoint2& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgPoint2& default_instance();

  static inline const MsgPoint2* internal_default_instance() {
    return reinterpret_cast<const MsgPoint2*>(
               &_MsgPoint2_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(MsgPoint2* other);

  // implements Message ----------------------------------------------

  inline MsgPoint2* New() const PROTOBUF_FINAL { return New(NULL); }

  MsgPoint2* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MsgPoint2& from);
  void MergeFrom(const MsgPoint2& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MsgPoint2* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required float x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // required float y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // @@protoc_insertion_point(class_scope:medical_imaging.MsgPoint2)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  float x_;
  float y_;
  friend struct protobuf_mi_5fmessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MsgPaging : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:medical_imaging.MsgPaging) */ {
 public:
  MsgPaging();
  virtual ~MsgPaging();

  MsgPaging(const MsgPaging& from);

  inline MsgPaging& operator=(const MsgPaging& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgPaging& default_instance();

  static inline const MsgPaging* internal_default_instance() {
    return reinterpret_cast<const MsgPaging*>(
               &_MsgPaging_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(MsgPaging* other);

  // implements Message ----------------------------------------------

  inline MsgPaging* New() const PROTOBUF_FINAL { return New(NULL); }

  MsgPaging* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MsgPaging& from);
  void MergeFrom(const MsgPaging& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MsgPaging* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 page = 1;
  bool has_page() const;
  void clear_page();
  static const int kPageFieldNumber = 1;
  ::google::protobuf::int32 page() const;
  void set_page(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:medical_imaging.MsgPaging)
 private:
  void set_has_page();
  void clear_has_page();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 page_;
  friend struct protobuf_mi_5fmessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MsgRotate : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:medical_imaging.MsgRotate) */ {
 public:
  MsgRotate();
  virtual ~MsgRotate();

  MsgRotate(const MsgRotate& from);

  inline MsgRotate& operator=(const MsgRotate& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgRotate& default_instance();

  static inline const MsgRotate* internal_default_instance() {
    return reinterpret_cast<const MsgRotate*>(
               &_MsgRotate_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(MsgRotate* other);

  // implements Message ----------------------------------------------

  inline MsgRotate* New() const PROTOBUF_FINAL { return New(NULL); }

  MsgRotate* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MsgRotate& from);
  void MergeFrom(const MsgRotate& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MsgRotate* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .medical_imaging.MsgPoint2 pre = 1;
  bool has_pre() const;
  void clear_pre();
  static const int kPreFieldNumber = 1;
  const ::medical_imaging::MsgPoint2& pre() const;
  ::medical_imaging::MsgPoint2* mutable_pre();
  ::medical_imaging::MsgPoint2* release_pre();
  void set_allocated_pre(::medical_imaging::MsgPoint2* pre);

  // required .medical_imaging.MsgPoint2 cur = 2;
  bool has_cur() const;
  void clear_cur();
  static const int kCurFieldNumber = 2;
  const ::medical_imaging::MsgPoint2& cur() const;
  ::medical_imaging::MsgPoint2* mutable_cur();
  ::medical_imaging::MsgPoint2* release_cur();
  void set_allocated_cur(::medical_imaging::MsgPoint2* cur);

  // @@protoc_insertion_point(class_scope:medical_imaging.MsgRotate)
 private:
  void set_has_pre();
  void clear_has_pre();
  void set_has_cur();
  void clear_has_cur();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::medical_imaging::MsgPoint2* pre_;
  ::medical_imaging::MsgPoint2* cur_;
  friend struct protobuf_mi_5fmessage_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgPoint2

// required float x = 1;
inline bool MsgPoint2::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgPoint2::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgPoint2::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgPoint2::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float MsgPoint2::x() const {
  // @@protoc_insertion_point(field_get:medical_imaging.MsgPoint2.x)
  return x_;
}
inline void MsgPoint2::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:medical_imaging.MsgPoint2.x)
}

// required float y = 2;
inline bool MsgPoint2::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgPoint2::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgPoint2::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgPoint2::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float MsgPoint2::y() const {
  // @@protoc_insertion_point(field_get:medical_imaging.MsgPoint2.y)
  return y_;
}
inline void MsgPoint2::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:medical_imaging.MsgPoint2.y)
}

// -------------------------------------------------------------------

// MsgPaging

// required int32 page = 1;
inline bool MsgPaging::has_page() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgPaging::set_has_page() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgPaging::clear_has_page() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgPaging::clear_page() {
  page_ = 0;
  clear_has_page();
}
inline ::google::protobuf::int32 MsgPaging::page() const {
  // @@protoc_insertion_point(field_get:medical_imaging.MsgPaging.page)
  return page_;
}
inline void MsgPaging::set_page(::google::protobuf::int32 value) {
  set_has_page();
  page_ = value;
  // @@protoc_insertion_point(field_set:medical_imaging.MsgPaging.page)
}

// -------------------------------------------------------------------

// MsgRotate

// required .medical_imaging.MsgPoint2 pre = 1;
inline bool MsgRotate::has_pre() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgRotate::set_has_pre() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgRotate::clear_has_pre() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgRotate::clear_pre() {
  if (pre_ != NULL) pre_->::medical_imaging::MsgPoint2::Clear();
  clear_has_pre();
}
inline const ::medical_imaging::MsgPoint2& MsgRotate::pre() const {
  // @@protoc_insertion_point(field_get:medical_imaging.MsgRotate.pre)
  return pre_ != NULL ? *pre_
                         : *::medical_imaging::MsgPoint2::internal_default_instance();
}
inline ::medical_imaging::MsgPoint2* MsgRotate::mutable_pre() {
  set_has_pre();
  if (pre_ == NULL) {
    pre_ = new ::medical_imaging::MsgPoint2;
  }
  // @@protoc_insertion_point(field_mutable:medical_imaging.MsgRotate.pre)
  return pre_;
}
inline ::medical_imaging::MsgPoint2* MsgRotate::release_pre() {
  // @@protoc_insertion_point(field_release:medical_imaging.MsgRotate.pre)
  clear_has_pre();
  ::medical_imaging::MsgPoint2* temp = pre_;
  pre_ = NULL;
  return temp;
}
inline void MsgRotate::set_allocated_pre(::medical_imaging::MsgPoint2* pre) {
  delete pre_;
  pre_ = pre;
  if (pre) {
    set_has_pre();
  } else {
    clear_has_pre();
  }
  // @@protoc_insertion_point(field_set_allocated:medical_imaging.MsgRotate.pre)
}

// required .medical_imaging.MsgPoint2 cur = 2;
inline bool MsgRotate::has_cur() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgRotate::set_has_cur() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgRotate::clear_has_cur() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgRotate::clear_cur() {
  if (cur_ != NULL) cur_->::medical_imaging::MsgPoint2::Clear();
  clear_has_cur();
}
inline const ::medical_imaging::MsgPoint2& MsgRotate::cur() const {
  // @@protoc_insertion_point(field_get:medical_imaging.MsgRotate.cur)
  return cur_ != NULL ? *cur_
                         : *::medical_imaging::MsgPoint2::internal_default_instance();
}
inline ::medical_imaging::MsgPoint2* MsgRotate::mutable_cur() {
  set_has_cur();
  if (cur_ == NULL) {
    cur_ = new ::medical_imaging::MsgPoint2;
  }
  // @@protoc_insertion_point(field_mutable:medical_imaging.MsgRotate.cur)
  return cur_;
}
inline ::medical_imaging::MsgPoint2* MsgRotate::release_cur() {
  // @@protoc_insertion_point(field_release:medical_imaging.MsgRotate.cur)
  clear_has_cur();
  ::medical_imaging::MsgPoint2* temp = cur_;
  cur_ = NULL;
  return temp;
}
inline void MsgRotate::set_allocated_cur(::medical_imaging::MsgPoint2* cur) {
  delete cur_;
  cur_ = cur;
  if (cur) {
    set_has_cur();
  } else {
    clear_has_cur();
  }
  // @@protoc_insertion_point(field_set_allocated:medical_imaging.MsgRotate.cur)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace medical_imaging

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_mi_5fmessage_2eproto__INCLUDED
