#ifndef MEDIMGARITHMETIC_MI_ARITHMETIC_LOGGER_H
#define MEDIMGARITHMETIC_MI_ARITHMETIC_LOGGER_H

#include "log/mi_logger.h"

#define MI_ARITHMETIC_LOG(sev) MI_LOG(sev) << "[Arithmetic] "
#define MI_ARITHMETIC_LOG_DETAIL(sev) MI_ARITHMETIC_LOG(sev) << MI_DETAIL_FORMAT

#endif